version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - portfolio-builder-db:/var/lib/postgresql/data

  pbserver:
    build:
      context: ./server
    depends_on:
      - postgres
    env_file:
      - ./server/.env.prod
    ports:
      - "5000:5000"
    volumes:
      - portfolio-builder-img:/app

  pbclient:
    build:
      context: ./client
    depends_on:
      - postgres
      - pbserver
    ports:
      - "3000:3000"

volumes:
  portfolio-builder-db: {}
  portfolio-builder-img: {}
